In [1]:
# %%
import pandas as pd 
import numpy as np
# import matplotlib.pyplot as plt 
# import seaborn as sns
import torch
from functools import partial
from openai import AsyncOpenAI

import sys, os
project_root = os.path.abspath(os.path.join(os.getcwd(), "../"))
if project_root not in sys.path:
    sys.path.append(project_root)

# Load .env from project root
from dotenv import load_dotenv
load_dotenv(os.path.join(project_root, ".env"))

from shared_functions.gg_sheet_drive import *

import ast

In [2]:
# Read model config from environment
LLM_MODEL = os.environ["LLM_MODEL"]
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", "nomic-ai/nomic-embed-text-v1.5")
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "http://127.0.0.1:8080/v1")
EMBED_BASE_URL = os.environ.get("EMBED_BASE_URL", "http://127.0.0.1:8081/v1")

print(f"LLM_MODEL     : {LLM_MODEL}")
print(f"EMBEDDING_MODEL: {EMBEDDING_MODEL}")
print(f"LLM_BASE_URL  : {LLM_BASE_URL}")
print(f"EMBED_BASE_URL : {EMBED_BASE_URL}")

import asyncio
from lightrag.utils import setup_logger, EmbeddingFunc
from lightrag.llm.hf import hf_embed
from lightrag import LightRAG, QueryParam
from lightrag.llm.openai import gpt_4o_mini_complete, gpt_4o_complete, openai_embed, openai_complete
from lightrag.utils import setup_logger

LLM_MODEL     : Qwen/Qwen2.5-7B-Instruct-AWQ
EMBEDDING_MODEL: nomic-ai/nomic-embed-text-v1.5
LLM_BASE_URL  : http://127.0.0.1:8080/v1
EMBED_BASE_URL : http://127.0.0.1:8081/v1

In [3]:
data_dir = os.path.join(project_root, 'data', 'external', 'medqa')

In [3]:
setup_logger("lightrag", level="INFO")

WORKING_DIR = "./rag_storage"
if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

### Ingestion

In [2]:
async def hf_model_complete(prompt: str, system_prompt=None, history_messages=[], **kwargs):
    device = model.device
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.extend(history_messages)
    messages.append({"role": "user", "content": prompt})
    
    # Use chat template to wrap the complex LightRAG instructions
    tokenized_chat = llm_tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True, return_tensors="pt")
    inputs = {"input_ids": tokenized_chat.to(device)}

    outputs = model.generate(
        **inputs,
        max_new_tokens=512,
        temperature=0.1,
        do_sample=True,
        pad_token_id=llm_tokenizer.eos_token_id
    )

    decoded = llm_tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    return decoded.strip()

In [3]:
async def llm_complete(prompt, system_prompt=None, history_messages=None, **kwargs):
    """LLM completion using the model configured in .env (LLM_MODEL)."""
    kwargs.update({
        "temperature": 0.1,
        "top_p": 0.95,
        "max_tokens": 1024,
    })

    return await openai_complete(
        prompt,
        system_prompt=system_prompt,
        history_messages=history_messages,
        **kwargs
    )

In [4]:
# Using vLLM — model name and URLs come from .env

rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=llm_complete,
    llm_model_name=LLM_MODEL,
    llm_model_max_async=4,
    llm_model_kwargs={
        "base_url": LLM_BASE_URL,
        "api_key": "none"
    },
    chunk_token_size=1200,
    entity_extract_max_gleaning=0,
    default_embedding_timeout=120,
    
    embedding_func=EmbeddingFunc(
        embedding_dim=768, 
        max_token_size=8192,
        func=partial(
            openai_embed.func,
            base_url=EMBED_BASE_URL,
            api_key="none",
            model=EMBEDDING_MODEL
        )
    )
)

INFO: [] Created new empty graph file: ./rag_storage/graph_chunk_entity_relation.graphml
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './rag_storage/vdb_entities.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './rag_storage/vdb_relationships.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './rag_storage/vdb_chunks.json'} 0 data

In [5]:
await rag.initialize_storages()

INFO: [] Process 908494 KV load full_docs with 0 records
INFO: [] Process 908494 KV load text_chunks with 0 records
INFO: [] Process 908494 KV load full_entities with 0 records
INFO: [] Process 908494 KV load full_relations with 0 records
INFO: [] Process 908494 KV load entity_chunks with 0 records
INFO: [] Process 908494 KV load relation_chunks with 0 records
INFO: [] Process 908494 KV load llm_response_cache with 0 records
INFO: [] Process 908494 doc status load doc_status with 0 records

In [ ]:
sample_textbook = os.path.join(data_dir, 'textbooks', 'Anatomy_Gray.txt')

with open(sample_textbook, 'r') as f:
    text = f.read()

In [10]:
await rag.ainsert(text)

WARNING: Duplicate document detected: doc-21250d6571086cc53d058350568a0609 (unknown_source)
INFO: Created 1 duplicate document records with track_id: insert_20260312_010439_5ed94aa4
WARNING: No new unique documents were found.
INFO: Preserving 1 failed document entries for manual review
INFO: Reset 1 documents from PROCESSING/FAILED to PENDING status
INFO: Processing 1 document(s)
INFO: Extracting stage 1/1: unknown_source
INFO: Processing d-id: doc-21250d6571086cc53d058350568a0609

WARNING: chunk-12ebe42e580fd1ab8c7674e6a0142868: Complete delimiter can not be found in extraction result
WARNING: chunk-8c530ec36bf9d30853dccf355f45d595: Complete delimiter can not be found in extraction result
WARNING: chunk-8c530ec36bf9d30853dccf355f45d595: LLM output format error; found 2/4 feilds on ENTITY `Intra-Arterial Contrast Agent` @ `N/A`
WARNING: chunk-11366959b155e9dcfcd79e0b923979de: Complete delimiter can not be found in extraction result
WARNING: chunk-0bc4d75894db09d737d9d47715131315: Complete delimiter can not be found in extraction result
INFO: Chunk 1 of 468 extracted 30 Ent + 0 Rel chunk-12ebe42e580fd1ab8c7674e6a0142868
INFO: Chunk 2 of 468 extracted 31 Ent + 0 Rel chunk-8c530ec36bf9d30853dccf355f45d595
INFO: Chunk 3 of 468 extracted 28 Ent + 3 Rel chunk-11366959b155e9dcfcd79e0b923979de
INFO: Chunk 4 of 468 extracted 27 Ent + 0 Rel chunk-0bc4d75894db09d737d9d47715131315
WARNING: chunk-c8dd6947aa114ed520c7cc1f226401e3: Complete delimiter can not be found in extraction result
WARNING: chunk-2622e0177e14919615609223a054c41f: Complete delimiter can not be found in extraction result
WARNING: chunk-2622e0177e14919615609223a054c41f: LLM output format error; found 4/5 fields on REALTION `Bone`~`Skull`
INFO: Chunk 5 of 468 extracted 28 Ent + 0 Rel chunk-c8dd6947aa114ed520c7cc1f226401e3
WARNING: chunk-65d8ba7d2670990dd9ac8863c0407af0: Complete delimiter can not be found in extraction result
WARNING: chunk-65d8ba7d2670990dd9ac8863c0407af0: LLM output format error; found 3/4 feilds on ENTITY `Symphyses` @ `concept<`
WARNING: chunk-0d0ff62c79cbf95bf7807d6a60f69b6c: Complete delimiter can not be found in extraction result
WARNING: chunk-0d0ff62c79cbf95bf7807d6a60f69b6c: LLM output format error; found 3/5 fields on REALTION `Small and Medium Veins`~`Blood Vessels`
INFO: Chunk 6 of 468 extracted 19 Ent + 7 Rel chunk-2622e0177e14919615609223a054c41f
WARNING: chunk-fcab2acd6c04fa7081aadd31f6063600: Complete delimiter can not be found in extraction result
WARNING: chunk-fcab2acd6c04fa7081aadd31f6063600: LLM output format error; found 4/5 fields on REALTION `Lymphatic Vessels`~`Intestinal Epithelium`
INFO: Chunk 7 of 468 extracted 25 Ent + 0 Rel chunk-65d8ba7d2670990dd9ac8863c0407af0
INFO: Chunk 8 of 468 extracted 15 Ent + 8 Rel chunk-0d0ff62c79cbf95bf7807d6a60f69b6c
INFO: Chunk 9 of 468 extracted 22 Ent + 4 Rel chunk-fcab2acd6c04fa7081aadd31f6063600
WARNING: chunk-6c6de0c22ff2e8ef1ba40e2629a57295: Complete delimiter can not be found in extraction result
WARNING: chunk-1239c16ee834c873f5b3ae9d38c5ff95: Complete delimiter can not be found in extraction result
WARNING: chunk-1239c16ee834c873f5b3ae9d38c5ff95: LLM output format error; found 4/5 fields on REALTION `Somatic Motor Nerves`~`Spinal Cord`
INFO: Chunk 10 of 468 extracted 25 Ent + 0 Rel chunk-6c6de0c22ff2e8ef1ba40e2629a57295
WARNING: chunk-75fd21d9ae2866f67ef0c5f8d27f0811: Complete delimiter can not be found in extraction result
WARNING: chunk-ef8a25cc25cc9f63f99fa2c0457005ea: Complete delimiter can not be found in extraction result
INFO: Chunk 11 of 468 extracted 22 Ent + 2 Rel chunk-1239c16ee834c873f5b3ae9d38c5ff95
WARNING: chunk-53bad1f60c5dd0d2050090b00faf6b70: Complete delimiter can not be found in extraction result
INFO: Chunk 12 of 468 extracted 21 Ent + 3 Rel chunk-75fd21d9ae2866f67ef0c5f8d27f0811
INFO: Chunk 13 of 468 extracted 23 Ent + 3 Rel chunk-ef8a25cc25cc9f63f99fa2c0457005ea
INFO: Chunk 14 of 468 extracted 28 Ent + 0 Rel chunk-53bad1f60c5dd0d2050090b00faf6b70
WARNING: chunk-aaece71d826f1bca103ac29fe65c98a9: Complete delimiter can not be found in extraction result
WARNING: chunk-aaece71d826f1bca103ac29fe65c98a9: LLM output format error; found 2/4 feilds on ENTITY `Spinal Ganglion` @ `N/A`
WARNING: chunk-4b469c1125e45053fd1e8bb575b87c25: Complete delimiter can not be found in extraction result
WARNING: chunk-4b469c1125e45053fd1e8bb575b87c25: LLM output format error; found 2/4 feilds on ENTITY `Paravertebral Sympathetic Trunk` @ `N/A`
INFO: Chunk 15 of 468 extracted 27 Ent + 0 Rel chunk-aaece71d826f1bca103ac29fe65c98a9
WARNING: chunk-21fbcefabb1468cd4a6b4162bce8a7df: Complete delimiter can not be found in extraction result
WARNING: chunk-2e476537954e12e0a7c118197942d9ca: Complete delimiter can not be found in extraction result
INFO: Chunk 16 of 468 extracted 26 Ent + 0 Rel chunk-4b469c1125e45053fd1e8bb575b87c25
WARNING: chunk-b276f18a0d126c9f94e117f202886a12: Complete delimiter can not be found in extraction result
WARNING: chunk-b276f18a0d126c9f94e117f202886a12: LLM output format error; found 2/4 feilds on ENTITY `Somatic Side Of The Nervous System<|#` @ `N/A`
INFO: Chunk 17 of 468 extracted 27 Ent + 0 Rel chunk-21fbcefabb1468cd4a6b4162bce8a7df
INFO: Chunk 18 of 468 extracted 21 Ent + 5 Rel chunk-2e476537954e12e0a7c118197942d9ca
INFO: Chunk 19 of 468 extracted 28 Ent + 0 Rel chunk-b276f18a0d126c9f94e117f202886a12
WARNING: chunk-7299e02303e640115ff18824ccfc8a51: Complete delimiter can not be found in extraction result
WARNING: chunk-5be43461f1124c88b161b9277aad3bdf: Complete delimiter can not be found in extraction result
INFO: Chunk 20 of 468 extracted 24 Ent + 3 Rel chunk-7299e02303e640115ff18824ccfc8a51
WARNING: chunk-db6af4cf83cb501ae1de8cca0411931f: Complete delimiter can not be found in extraction result
WARNING: chunk-8bf4752fda3c79fe5e1b06d53790fab7: Complete delimiter can not be found in extraction result
WARNING: chunk-8bf4752fda3c79fe5e1b06d53790fab7: LLM output format error; found 4/5 fields on REALTION `Vertebra`~`Atlas`
INFO: Chunk 21 of 468 extracted 24 Ent + 0 Rel chunk-5be43461f1124c88b161b9277aad3bdf
INFO: Chunk 22 of 468 extracted 27 Ent + 1 Rel chunk-db6af4cf83cb501ae1de8cca0411931f
INFO: Chunk 23 of 468 extracted 17 Ent + 5 Rel chunk-8bf4752fda3c79fe5e1b06d53790fab7
INFO: Chunk 24 of 468 extracted 9 Ent + 8 Rel chunk-a01bb3408f5ef8bf9bf70b077f4f60cf
WARNING: chunk-942ab7c7ed660a8305379eea377fd9c4: Complete delimiter can not be found in extraction result
WARNING: chunk-7d6148c0c661bbd8464d298126eb41f5: Complete delimiter can not be found in extraction result
WARNING: chunk-7d6148c0c661bbd8464d298126eb41f5: LLM output format error; found 3/4 feilds on ENTITY `Splenius Capitis` @ `artifact<|#`
INFO: Chunk 25 of 468 extracted 22 Ent + 3 Rel chunk-942ab7c7ed660a8305379eea377fd9c4
WARNING: chunk-1b92d8282f88d72146897be728d70011: Complete delimiter can not be found in extraction result
WARNING: chunk-1b92d8282f88d72146897be728d70011: LLM output format error; found 2/5 fields on REALTION `Um`~`N/A`
WARNING: chunk-80a8ccff80268f8f10788bece56c0160: Complete delimiter can not be found in extraction result
WARNING: chunk-80a8ccff80268f8f10788bece56c0160: LLM output format error; found 3/5 fields on REALTION `Spinal Cord`~`Axis`
INFO: Chunk 26 of 468 extracted 24 Ent + 0 Rel chunk-7d6148c0c661bbd8464d298126eb41f5
WARNING: chunk-332cbfb7ccb4323d50c7ce7447a3c67a: Complete delimiter can not be found in extraction result
INFO: Chunk 27 of 468 extracted 19 Ent + 3 Rel chunk-1b92d8282f88d72146897be728d70011
INFO: Chunk 28 of 468 extracted 14 Ent + 8 Rel chunk-80a8ccff80268f8f10788bece56c0160
INFO: Chunk 29 of 468 extracted 18 Ent + 4 Rel chunk-332cbfb7ccb4323d50c7ce7447a3c67a
WARNING: chunk-b6a75f3f5d5d76e9ab8a2286bec5980f: Complete delimiter can not be found in extraction result
WARNING: chunk-e5ad51712d8542732ba11a6d11493b19: Complete delimiter can not be found in extraction result
INFO: Chunk 30 of 468 extracted 21 Ent + 1 Rel chunk-b6a75f3f5d5d76e9ab8a2286bec5980f
WARNING: chunk-70bfbba203cb237f71f6a1912612a37e: Complete delimiter can not be found in extraction result
WARNING: chunk-70bfbba203cb237f71f6a1912612a37e: LLM output format error; found 2/5 fields on REALTION `Vertebra LIII<`~`N/A`
WARNING: chunk-6bb7d51487dda2710729884b06cf5283: Complete delimiter can not be found in extraction result
WARNING: chunk-6bb7d51487dda2710729884b06cf5283: LLM output format error; found 2/5 fields on REALTION `Intervertebral Foramina<|#`~`N/A`
INFO: Chunk 31 of 468 extracted 27 Ent + 0 Rel chunk-e5ad51712d8542732ba11a6d11493b19
WARNING: chunk-147ee8016a5e3e28d264095692973da5: Complete delimiter can not be found in extraction result
WARNING: chunk-147ee8016a5e3e28d264095692973da5: LLM output format error; found 3/4 feilds on ENTITY `Ligamentum Flavum Hypertrophy` @ `condition`
INFO: Chunk 32 of 468 extracted 21 Ent + 3 Rel chunk-70bfbba203cb237f71f6a1912612a37e
INFO: Chunk 33 of 468 extracted 14 Ent + 8 Rel chunk-6bb7d51487dda2710729884b06cf5283
INFO: Chunk 34 of 468 extracted 26 Ent + 0 Rel chunk-147ee8016a5e3e28d264095692973da5
WARNING: chunk-86b6aa25630e92e6ebc60c6ad4b884ae: Complete delimiter can not be found in extraction result
INFO: Chunk 35 of 468 extracted 28 Ent + 0 Rel chunk-86b6aa25630e92e6ebc60c6ad4b884ae
WARNING: chunk-a91923599324804f572662251aebb98d: Complete delimiter can not be found in extraction result
WARNING: chunk-c439d489a5379d7744739dd646422546: Complete delimiter can not be found in extraction result
INFO: Chunk 36 of 468 extracted 7 Ent + 6 Rel chunk-860ec1263fdcd50924927583041e7777
WARNING: chunk-122745e291ea9c3dd3951d1f94c320a0: Complete delimiter can not be found in extraction result
WARNING: chunk-122745e291ea9c3dd3951d1f94c320a0: LLM output format error; found 2/4 feilds on ENTITY `Sacral Vertebrae<|#` @ `N/A`
INFO: Chunk 37 of 468 extracted 20 Ent + 5 Rel chunk-a91923599324804f572662251aebb98d
INFO: Chunk 38 of 468 extracted 22 Ent + 0 Rel chunk-c439d489a5379d7744739dd646422546
INFO: Chunk 39 of 468 extracted 25 Ent + 0 Rel chunk-122745e291ea9c3dd3951d1f94c320a0
WARNING: chunk-6fe78d0ab4438801c42d4c64ab2a57f3: Complete delimiter can not be found in extraction result
WARNING: chunk-6fe78d0ab4438801c42d4c64ab2a57f3: LLM output format error; found 3/5 fields on REALTION `Cauda Equina Syndrome`~`S3, S`
WARNING: chunk-7f9b8dfd51ec8be78087829343ae2153: Complete delimiter can not be found in extraction result
INFO: Chunk 40 of 468 extracted 16 Ent + 6 Rel chunk-6fe78d0ab4438801c42d4c64ab2a57f3
WARNING: chunk-5bc2aee4cbea47fd4ac3871c297b6eb9: Complete delimiter can not be found in extraction result
WARNING: chunk-5bc2aee4cbea47fd4ac3871c297b6eb9: LLM output format error; found 4/5 fields on REALTION `Patient`~`Adamkiewicz Artery`
WARNING: chunk-51d4e55146ce43fef5a150c46fc16a5a: Complete delimiter can not be found in extraction result
INFO: Chunk 41 of 468 extracted 26 Ent + 0 Rel chunk-7f9b8dfd51ec8be78087829343ae2153
WARNING: chunk-de07e3711b050ae56f845d8e420a9065: Complete delimiter can not be found in extraction result
INFO: Chunk 42 of 468 extracted 18 Ent + 5 Rel chunk-5bc2aee4cbea47fd4ac3871c297b6eb9
INFO: Chunk 43 of 468 extracted 24 Ent + 0 Rel chunk-51d4e55146ce43fef5a150c46fc16a5a
INFO: Chunk 44 of 468 extracted 20 Ent + 6 Rel chunk-de07e3711b050ae56f845d8e420a9065
WARNING: chunk-51fa72eabfeb24e0f839167e184206c3: Complete delimiter can not be found in extraction result
WARNING: chunk-51fa72eabfeb24e0f839167e184206c3: LLM output format error; found 4/5 fields on REALTION `Inferior Vena Cava`~`Diaphragm`
WARNING: chunk-e9eb26d84a2b27542084b1e3bd28039d: Complete delimiter can not be found in extraction result
INFO: Chunk 45 of 468 extracted 27 Ent + 0 Rel chunk-51fa72eabfeb24e0f839167e184206c3
WARNING: chunk-8d92948f93a5f1180de4255c31f9f3e4: Complete delimiter can not be found in extraction result
WARNING: chunk-8d92948f93a5f1180de4255c31f9f3e4: LLM output format error; found 3/4 feilds on ENTITY `Transverse Process` @ `artifact<`
WARNING: chunk-9b7a313acd14065c555768da892319f6: Complete delimiter can not be found in extraction result
INFO: Chunk 46 of 468 extracted 29 Ent + 0 Rel chunk-e9eb26d84a2b27542084b1e3bd28039d
WARNING: chunk-4fbbac42d551ed7cbd002fb2897eab24: Complete delimiter can not be found in extraction result
WARNING: chunk-4fbbac42d551ed7cbd002fb2897eab24: LLM output format error; found 4/5 fields on REALTION `Sternum`~`Costal Margin`
INFO: Chunk 47 of 468 extracted 28 Ent + 0 Rel chunk-8d92948f93a5f1180de4255c31f9f3e4
INFO: Chunk 48 of 468 extracted 12 Ent + 13 Rel chunk-9b7a313acd14065c555768da892319f6
INFO: Chunk 49 of 468 extracted 18 Ent + 6 Rel chunk-4fbbac42d551ed7cbd002fb2897eab24
WARNING: chunk-9c7dd5464e5f2b331a3940fcdfadc011: Complete delimiter can not be found in extraction result
WARNING: chunk-2e1d1acdda0c51c678b84c5a25477516: Complete delimiter can not be found in extraction result
WARNING: chunk-2e1d1acdda0c51c678b84c5a25477516: LLM output format error; found 4/5 fields on REALTION `Internal Thoracic Vessels`~`Thoracic Wall`
INFO: Chunk 50 of 468 extracted 21 Ent + 4 Rel chunk-9c7dd5464e5f2b331a3940fcdfadc011
WARNING: chunk-1dc6e7ec951c969467277c87d95f6863: Complete delimiter can not be found in extraction result
WARNING: chunk-1dc6e7ec951c969467277c87d95f6863: LLM output format error; found 2/4 feilds on ENTITY `Per` @ `N/A`
WARNING: chunk-da866f835262ce5417ae9b2759694684: Complete delimiter can not be found in extraction result
INFO: Chunk 51 of 468 extracted 24 Ent + 1 Rel chunk-2e1d1acdda0c51c678b84c5a25477516
WARNING: chunk-f5973864705aa471807026374bf77b74: Complete delimiter can not be found in extraction result
WARNING: chunk-f5973864705aa471807026374bf77b74: LLM output format error; found 2/5 fields on REALTION `Vagus Nerves`~`N/A`
INFO: Chunk 52 of 468 extracted 24 Ent + 0 Rel chunk-1dc6e7ec951c969467277c87d95f6863
INFO: Chunk 53 of 468 extracted 18 Ent + 5 Rel chunk-da866f835262ce5417ae9b2759694684
INFO: Chunk 54 of 468 extracted 17 Ent + 10 Rel chunk-f5973864705aa471807026374bf77b74
WARNING: chunk-9fc3329e73af976dd5ab0b38601a3bb6: Complete delimiter can not be found in extraction result
WARNING: chunk-3835cee4e5848cad9a88a6d7bd822b6b: Complete delimiter can not be found in extraction result
WARNING: chunk-3835cee4e5848cad9a88a6d7bd822b6b: LLM output format error; found 3/5 fields on REALTION `Pulmonary Trunk`~`Left`
INFO: Chunk 55 of 468 extracted 30 Ent + 0 Rel chunk-9fc3329e73af976dd5ab0b38601a3bb6
WARNING: chunk-e2c742b0a20349e726e7dd8bc665770c: Complete delimiter can not be found in extraction result
WARNING: chunk-e2c742b0a20349e726e7dd8bc665770c: LLM output format error; found 2/5 fields on REALTION `Posterior Mediastinum`~`N/A`
WARNING: chunk-e130e28dfac3379dcda2ff05cbdc4cd6: Complete delimiter can not be found in extraction result
WARNING: chunk-e130e28dfac3379dcda2ff05cbdc4cd6: LLM output format error; found 2/4 feilds on ENTITY `Right Margin` @ `N/A`
INFO: Chunk 56 of 468 extracted 17 Ent + 7 Rel chunk-3835cee4e5848cad9a88a6d7bd822b6b
WARNING: chunk-d907b3dca8c476e56cbc74f165b5e690: Complete delimiter can not be found in extraction result
INFO: Chunk 57 of 468 extracted 22 Ent + 2 Rel chunk-e2c742b0a20349e726e7dd8bc665770c
INFO: Chunk 58 of 468 extracted 21 Ent + 0 Rel chunk-e130e28dfac3379dcda2ff05cbdc4cd6
INFO: Chunk 59 of 468 extracted 24 Ent + 0 Rel chunk-d907b3dca8c476e56cbc74f165b5e690
WARNING: chunk-82c2d6a98ed33bd08a4e8c51989dbee9: Complete delimiter can not be found in extraction result
WARNING: chunk-620e3984579605f887ff871fb473f1ea: Complete delimiter can not be found in extraction result
INFO: Chunk 60 of 468 extracted 17 Ent + 4 Rel chunk-82c2d6a98ed33bd08a4e8c51989dbee9
WARNING: chunk-4e5cb3e0e303697fbb39d35fd7245e10: Complete delimiter can not be found in extraction result
WARNING: chunk-41df1ab423d91dabadfeb2ac89aa5382: Complete delimiter can not be found in extraction result
WARNING: chunk-41df1ab423d91dabadfeb2ac89aa5382: LLM output format error; found 2/5 fields on REALTION `Sinu-Atrial Node<|#`~`N/A`
INFO: Chunk 61 of 468 extracted 19 Ent + 4 Rel chunk-620e3984579605f887ff871fb473f1ea
WARNING: chunk-ff9d64fd6d5e4a5ae24edd1ec430929f: Complete delimiter can not be found in extraction result
INFO: Chunk 62 of 468 extracted 20 Ent + 4 Rel chunk-4e5cb3e0e303697fbb39d35fd7245e10
INFO: Chunk 63 of 468 extracted 12 Ent + 8 Rel chunk-41df1ab423d91dabadfeb2ac89aa5382
INFO: Chunk 64 of 468 extracted 21 Ent + 2 Rel chunk-ff9d64fd6d5e4a5ae24edd1ec430929f
WARNING: chunk-a125d5d1da1f3d7d3c9905607c9e1b65: Complete delimiter can not be found in extraction result
WARNING: chunk-a125d5d1da1f3d7d3c9905607c9e1b65: LLM output format error; found 2/4 feilds on ENTITY `Internal Thoracic Artery` @ `N/A`
WARNING: chunk-f2bf7e13e75147ce9b525dbfdf6fbfe6: Complete delimiter can not be found in extraction result
INFO: Chunk 65 of 468 extracted 21 Ent + 0 Rel chunk-a125d5d1da1f3d7d3c9905607c9e1b65
WARNING: chunk-4cd7ef325de22e68171d5c5cd5770400: Complete delimiter can not be found in extraction result
WARNING: chunk-4cd7ef325de22e68171d5c5cd5770400: LLM output format error; found 3/5 fields on REALTION `Azygos Vein`~`Esophagus<`
WARNING: chunk-30e7aa5df7f9fa73f72a8f1a53c6ffba: Complete delimiter can not be found in extraction result
INFO: Chunk 66 of 468 extracted 23 Ent + 0 Rel chunk-f2bf7e13e75147ce9b525dbfdf6fbfe6
WARNING: chunk-8a1266b3aba30d89ef8db9aeb97fa277: Complete delimiter can not be found in extraction result
INFO: Chunk 67 of 468 extracted 13 Ent + 7 Rel chunk-4cd7ef325de22e68171d5c5cd5770400
INFO: Chunk 68 of 468 extracted 23 Ent + 0 Rel chunk-30e7aa5df7f9fa73f72a8f1a53c6ffba
INFO: Chunk 69 of 468 extracted 23 Ent + 1 Rel chunk-8a1266b3aba30d89ef8db9aeb97fa277
WARNING: chunk-97355d9ae637c17bcf2d4b9b5a75ff6a: Complete delimiter can not be found in extraction result
WARNING: chunk-a012477b06b71a8f94368e9f55160b7a: Complete delimiter can not be found in extraction result
INFO: Chunk 70 of 468 extracted 24 Ent + 0 Rel chunk-97355d9ae637c17bcf2d4b9b5a75ff6a
WARNING: chunk-5ffb5419cd8ef2ddd144b23847964aa4: Complete delimiter can not be found in extraction result
WARNING: chunk-f0c2011e7575c7986b8a84695b612a8d: Complete delimiter can not be found in extraction result
INFO: Chunk 71 of 468 extracted 24 Ent + 0 Rel chunk-a012477b06b71a8f94368e9f55160b7a
WARNING: chunk-84b11d14febf691bfb87fafbb172905c: Complete delimiter can not be found in extraction result
WARNING: chunk-84b11d14febf691bfb87fafbb172905c: LLM output format error; found 2/4 feilds on ENTITY `Medial Bronchopulmonary Segment` @ `N/A`
INFO: Chunk 72 of 468 extracted 29 Ent + 0 Rel chunk-5ffb5419cd8ef2ddd144b23847964aa4
INFO: Chunk 73 of 468 extracted 27 Ent + 0 Rel chunk-f0c2011e7575c7986b8a84695b612a8d
INFO: Chunk 74 of 468 extracted 26 Ent + 0 Rel chunk-84b11d14febf691bfb87fafbb172905c
WARNING: chunk-abbe24590aa631d6644ae10b25a3cdb7: Complete delimiter can not be found in extraction result
WARNING: chunk-9e7346353c4534518780c86205e701d0: Complete delimiter can not be found in extraction result
INFO: Chunk 75 of 468 extracted 26 Ent + 0 Rel chunk-abbe24590aa631d6644ae10b25a3cdb7
WARNING: chunk-3cba2ca3f2e298a105c944f5be677ba1: Complete delimiter can not be found in extraction result
WARNING: chunk-704e8a6c5402d492dd79f6b99fab22b4: Complete delimiter can not be found in extraction result
WARNING: chunk-704e8a6c5402d492dd79f6b99fab22b4: LLM output format error; found 2/4 feilds on ENTITY `Latissimus D` @ `N/A`
INFO: Chunk 76 of 468 extracted 23 Ent + 0 Rel chunk-9e7346353c4534518780c86205e701d0
WARNING: chunk-a627619a87e5023e1b78f56be13a0ce5: Complete delimiter can not be found in extraction result
WARNING: chunk-a627619a87e5023e1b78f56be13a0ce5: LLM output format error; found 3/4 feilds on ENTITY `Mastectomy` @ `procedure`
INFO: Chunk 77 of 468 extracted 27 Ent + 0 Rel chunk-3cba2ca3f2e298a105c944f5be677ba1
INFO: Chunk 78 of 468 extracted 30 Ent + 0 Rel chunk-704e8a6c5402d492dd79f6b99fab22b4
INFO: Chunk 79 of 468 extracted 26 Ent + 0 Rel chunk-a627619a87e5023e1b78f56be13a0ce5
WARNING: chunk-9b7a4e3d7b0c28fcd4e954136d030979: Complete delimiter can not be found in extraction result
WARNING: chunk-2a94d533f81891309c609fc3def24b24: Complete delimiter can not be found in extraction result
INFO: Chunk 80 of 468 extracted 29 Ent + 0 Rel chunk-9b7a4e3d7b0c28fcd4e954136d030979
WARNING: chunk-e2aaf674c48e68ad6ca9286bb027309a: Complete delimiter can not be found in extraction result
WARNING: chunk-84a8d549069754807c90edb63e7c8db1: Complete delimiter can not be found in extraction result

'insert_20260312_010439_5ed94aa4'

## 🧪 Model Test Block

Use the cells below to test the LLM and embedding servers independently, **without** needing a full RAG pipeline.

#### Unit test

In [11]:
# --- Test: Direct LLM call via OpenAI-compatible API ---
from openai import AsyncOpenAI

llm_client = AsyncOpenAI(base_url=LLM_BASE_URL, api_key="none")

TEST_PROMPT = "What are the main causes of hypertension? Answer in 3 bullet points."
TEST_SYSTEM  = "You are a helpful medical assistant."

response = await llm_client.chat.completions.create(
    model=LLM_MODEL,
    messages=[
        {"role": "system", "content": TEST_SYSTEM},
        {"role": "user",   "content": TEST_PROMPT},
    ],
    temperature=0.1,
    max_tokens=512,
)

print(f"Model  : {response.model}")
print(f"Tokens : prompt={response.usage.prompt_tokens}, completion={response.usage.completion_tokens}")
print("\n--- Response ---")
print(response.choices[0].message.content)

Model  : Qwen/Qwen2.5-7B-Instruct-AWQ
Tokens : prompt=35, completion=84

--- Response ---
- **Genetic Factors**: A family history of hypertension can increase an individual's risk.
- **Lifestyle Choices**: Poor diet (high in sodium and low in potassium), lack of physical activity, obesity, and excessive alcohol consumption contribute to hypertension.
- **Age and Gender**: Risk increases with age, and men are more likely to develop hypertension than women until menopause, after which the risk for women rises.

In [ ]:
# --- Test: Embedding server ---
embed_client = AsyncOpenAI(base_url=EMBED_BASE_URL, api_key="none")

TEST_TEXT = "The heart pumps blood throughout the body."

embed_response = await embed_client.embeddings.create(
    model=EMBEDDING_MODEL,
    input=TEST_TEXT,
)

vec = embed_response.data[0].embedding
print(f"Embedding model : {EMBEDDING_MODEL}")
print(f"Vector dimension: {len(vec)}")
print(f"First 8 values  : {vec[:8]}")

Embedding model : nomic-ai/nomic-embed-text-v1.5
Vector dimension: 768
First 8 values  : [1.65087890625, 1.772070288658142, -4.043164253234863, 0.4876464903354645, 0.6470062136650085, 0.508770763874054, -0.3969482481479645, 1.058740258216858]

In [16]:
# --- Test: RAG query (requires storages to be initialized and documents inserted) ---
QUERY = "What is the function of the aorta?"
MODE  = "local"  # options: naive | local | global | hybrid

result = await rag.aquery(QUERY, param=QueryParam(mode=MODE))
print(f"Query : {QUERY}")
print(f"Mode  : {MODE}")
print("\n--- Answer ---")
print(result)

INFO:  == LLM cache == saving: local:keywords:2f9f2453fc68080144ef03235d72eaad
INFO: Query nodes: Blood transport, Arterial system, Cardiovascular function (top_k:40, cosine:0.2)
INFO: Local query: 40 entites, 18 relations
INFO: Raw search results: 40 entities, 18 relations, 0 vector chunks
INFO: After truncation: 40 entities, 18 relations
INFO: Selecting 85 from 85 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 18 relations
INFO: Round-robin merged chunks: 85 -> 85 (deduplicated 0)
WARNING: Rerank is enabled but no rerank model is configured. Please set up a rerank model or set enable_rerank=False in query parameters.
INFO: Final context: 40 entities, 18 relations, 20 chunks
INFO: Final chunks S+F/O: E1/1 E1/2 E1/3 E1/4 E3/5 E1/6 E2/7 E2/8 E1/9 E1/10 E2/11 E2/12 E1/13 E1/14 E3/15 E1/16 E3/17 E2/18 E1/19 E1/20
ERROR: Query failed: Error code: 400 - {'error': {'message': "You passed 7169 input tokens and requested 1024 output tokens. However, the model's context length is only 8192 tokens, resulting in a maximum input length of 7168 tokens. Please reduce the length of the input prompt. (parameter=input_tokens, value=7169)", 'type': 'BadRequestError', 'param': 'input_tokens', 'code': 400}}

Query : What is the function of the aorta?
Mode  : local

--- Answer ---
None

#### QA Test

In [4]:
from test_full_pipeline import BioMed_RAG

bio_hehe = BioMed_RAG()

LLM_MODEL     : Qwen/Qwen2.5-7B-Instruct-AWQ
EMBEDDING_MODEL: nomic-ai/nomic-embed-text-v1.5
LLM_BASE_URL  : http://127.0.0.1:8080/v1
EMBED_BASE_URL : http://127.0.0.1:8081/v1

In [5]:
qa_path = os.path.join(data_dir, 'medqa_form1.csv')

medqa = pd.read_csv(qa_path, index_col = 0)

medqa = medqa.drop_duplicates(subset = 'question')

In [6]:
unqa = medqa[medqa['processed'] == 0].copy()

unqa['answer'] = unqa.apply(
    lambda row: ast.literal_eval(row['options'])[row['answer']],
    axis=1
)

new_qa = pd.concat([medqa[medqa['processed'] == 1], unqa], axis = 0)

new_qa = new_qa[['question', 'answer']]

In [7]:
new_qa

,question,answer
0,A 23-year-old pregnant woman at 22 weeks gesta...,Nitrofurantoin
1,A 3-month-old baby died suddenly at night whil...,Placing the infant in a supine position on a f...
2,A mother brings her 3-week-old infant to the p...,Abnormal migration of ventral pancreatic bud
3,A pulmonary autopsy specimen from a 58-year-ol...,Thromboembolism
4,A 20-year-old woman presents with menorrhagia ...,Von Willebrand disease
...,...,...
14328,A 75-year-old man presents to his physician af...,Hepatotoxicity
14341,The brain of a 75-year-old man is reviewed at ...,Cytoplasmic inclusions of tau protein
14348,A 55-year-old male presents with a low grade f...,Coccidioidomycosis
14354,A 36-year-old man working as a hospital techni...,Mutation of cell wall D-ala-D-ala to D-ala-D-lac
14357,A 21-year-old university student is found unco...,Neisseria meningitidis

In [8]:
sample_qa = new_qa.head(5).copy()

sample_qa['llm_answer'] = ''

for i in range(sample_qa.shape[0]):
    sample_qa.loc[i, 'llm_answer'], sample_qa.loc[i, 'retrieved_context'] = await bio_hehe.biomedical_rag(sample_qa.loc[i, 'question'])

INFO: [] Loaded graph from ./rag_storage/graph_chunk_entity_relation.graphml with 5252 nodes, 1000 edges
INFO:nano-vectordb:Load (5252, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './rag_storage/vdb_entities.json'} 5252 data
INFO:nano-vectordb:Load (1000, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './rag_storage/vdb_relationships.json'} 1000 data
INFO:nano-vectordb:Load (468, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './rag_storage/vdb_chunks.json'} 468 data
INFO: [] Process 1136714 KV load full_docs with 1 records
INFO: [] Process 1136714 KV load text_chunks with 468 records
INFO: [] Process 1136714 KV load full_entities with 1 records
INFO: [] Process 1136714 KV load full_relations with 1 records
INFO: [] Process 1136714 KV load entity_chunks with 5252 records
INFO: [] Process 1136714 KV load relation_chunks with 1000 records
INFO: [] Process 1136714 KV load llm_response_cache with 679 records
INFO: [] Process 1136714 doc status load doc_status with 2 records
INFO: Embedding func: 8 new workers initialized (Timeouts: Func: 120s, Worker: 240s, Health Check: 255s)
INFO: Query nodes: 22 weeks gestation, Costovertebral angle tenderness, Gravid uterus, Cranberry extract, Temperature, Blood pressure, Pulse, Respirations, Oxygen saturation (top_k:15, cosine:0.2)
INFO: Local query: 15 entites, 4 relations
INFO: Query edges: Pregnant woman, Burning upon urination, Treatment (top_k:15, cosine:0.2)
INFO: Global query: 21 entites, 15 relations
INFO: Raw search results: 36 entities, 19 relations, 0 vector chunks
INFO: After truncation: 27 entities, 19 relations
INFO: Selecting 61 from 61 entity-related chunks by vector similarity
INFO: Find 1 additional chunks in 1 relations (deduplicated 10)
INFO: Selecting 1 from 1 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 62 -> 62 (deduplicated 0)
INFO: Final context: 27 entities, 19 relations, 4 chunks
INFO: Final chunks S+F/O: E4/1 R1/1 E1/2 E5/3
INFO: Query nodes: Safe sleep environment, Supervision during sleep, Crib safety, Binky, Sleep position (top_k:15, cosine:0.2)
INFO: Local query: 15 entites, 6 relations
INFO: Query edges: Sudden infant death, Infant safety, Autopsy, Precautions (top_k:15, cosine:0.2)
INFO: Global query: 25 entites, 15 relations
INFO: Raw search results: 39 entities, 20 relations, 0 vector chunks
INFO: After truncation: 23 entities, 20 relations
INFO: Selecting 57 from 72 entity-related chunks by vector similarity
INFO: Find 7 additional chunks in 7 relations (deduplicated 9)
INFO: Selecting 7 from 7 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 64 -> 64 (deduplicated 0)
INFO: Final context: 23 entities, 20 relations, 4 chunks
INFO: Final chunks S+F/O: E1/1 R1/1 E2/2 R1/2
INFO: Query nodes: Infantile gastroesophageal reflux, Congenital anomalies, Abdominal distension, Embryonic development, Gastrointestinal issues (top_k:15, cosine:0.2)
INFO: Local query: 15 entites, 10 relations
INFO: Query edges: Pediatrician visit, Infant feeding habits, Embryologic errors, Fussy infant, Regurgitation, Yellow vomit (top_k:15, cosine:0.2)
INFO: Global query: 21 entites, 15 relations
INFO: Raw search results: 36 entities, 25 relations, 0 vector chunks
INFO: After truncation: 31 entities, 25 relations
INFO: Selecting 70 from 70 entity-related chunks by vector similarity
INFO: Find 2 additional chunks in 2 relations (deduplicated 15)
INFO: Selecting 2 from 2 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 72 -> 72 (deduplicated 0)
INFO: Final context: 31 entities, 25 relations, 4 chunks
INFO: Final chunks S+F/O: E3/1 R1/1 E2/2 R1/2
INFO: Query nodes: 58-year-old woman, Cardiac arrest, Shortness of breath, Fractured femur, Rehab facility, Lung tissue, Histological examination findings (top_k:15, cosine:0.2)
INFO: Local query: 15 entites, 45 relations
INFO: Query edges: Pulmonary autopsy, Acute hypoxic respiratory failure, Femur fracture, Rehabilitation, Histological examination, Fibrous connective tissue, Pulmonary artery, Pathogenesis (top_k:15, cosine:0.2)
INFO: Global query: 25 entites, 15 relations
INFO: Raw search results: 35 entities, 55 relations, 0 vector chunks
INFO: After truncation: 31 entities, 50 relations
INFO: Selecting 65 from 65 entity-related chunks by vector similarity
INFO: Find 2 additional chunks in 2 relations (deduplicated 15)
INFO: Selecting 2 from 2 relation-related chunks by vector similarity
INFO: Round-robin merged chunks: 67 -> 67 (deduplicated 0)
INFO: Final context: 31 entities, 50 relations, 4 chunks
INFO: Final chunks S+F/O: E2/1 R1/1 E3/2 R1/2
INFO: Query nodes: 20-year-old woman, Mother, Heart rate, Respiratory rate, Temperature, Blood pressure, 200,000/mm3, 12 seconds, 43 seconds, Thrombocytopenia, Prolonged coagulation time (top_k:15, cosine:0.2)
INFO: Local query: 15 entites, 9 relations
INFO: Query edges: Menorrhagia, Easy bruising, Family history, Platelet count, PT, PTT, Thrombocytopenia, Coagulation disorder (top_k:15, cosine:0.2)
INFO: Global query: 26 entites, 15 relations
INFO: Raw search results: 40 entities, 23 relations, 0 vector chunks
INFO: After truncation: 39 entities, 23 relations
INFO: Selecting 42 from 42 entity-related chunks by vector similarity
INFO: Find no additional relations-related chunks from 23 relations
INFO: Round-robin merged chunks: 42 -> 42 (deduplicated 0)
INFO: Final context: 39 entities, 23 relations, 4 chunks
INFO: Final chunks S+F/O: E2/1 E6/2 E1/3 E1/4

In [9]:
sample_qa

,question,answer,llm_answer,retrieved_context
0,A 23-year-old pregnant woman at 22 weeks gesta...,Nitrofurantoin,The retrieved context does not contain this in...,\nKnowledge Graph Data (Entity):\n\n```json\n{...
1,A 3-month-old baby died suddenly at night whil...,Placing the infant in a supine position on a f...,Place the baby on its back to sleep.,\nKnowledge Graph Data (Entity):\n\n```json\n{...
2,A mother brings her 3-week-old infant to the p...,Abnormal migration of ventral pancreatic bud,Gastroesophageal Reflux\n\nThis condition can ...,\nKnowledge Graph Data (Entity):\n\n```json\n{...
3,A pulmonary autopsy specimen from a 58-year-ol...,Thromboembolism,Fibrosis of the pulmonary artery lumen suggest...,\nKnowledge Graph Data (Entity):\n\n```json\n{...
4,A 20-year-old woman presents with menorrhagia ...,Von Willebrand disease,The retrieved context does not contain this in...,\nKnowledge Graph Data (Entity):\n\n```json\n{...

In [ ]:
# write_df_to_gs(sample_qa, 'Qwen2.5-7B-Instruct-AWQ_nomic-embed-text-v1.5')

'DataFrame appended to existing Google Sheet tab: Qwen2.5-7B-Instruct-AWQ_nomic-embed-text-v1.5'

## Evaluation